---
# Welcome to my Home Assistant configuration!
#
# The configuration.yaml is only used to bootstrap the system
# and contains some minimal, but vital, settings.
#
homeassistant:
  # Name of this Home Assistant instance
  name: Home

   # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich

  # Load packages
  # packages: !include_dir_named packages
  packages: !include_dir_named integrations
  
  whitelist_external_dirs:
   - /tmp
   - /share

# Enables Person Component
person:
  - name: Tobias
    id: tobias
    user_id: 2d566e55d2ef48b1a45bf32ad07a7338
    device_trackers:
      - device_tracker.galaxy_s8_wifi
      - device_tracker.galaxy_s8_bt
  - name: Laura
    id: laura
    user_id: 219a1399fb684a329e6831348c5c8222
    device_trackers:
      - device_tracker.iphone6

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
