---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
resources: !include_dir_list lovelace/resources

# -----------------------------
## music player
x-music-player: &music-player
  icon: 'mdi:speaker-wireless'
  hide:
    power_state: false
    source: false
    icon: true
    progress: true
  group: true
  artwork: none
  source: full
  more_info: false
  replace_mute: stop

## vacuum_buttons
x-vacuum-buttons: &vacuum-buttons
  show_name: false
  color_type: icon
  color: rgb(68, 115, 158)
  entity: vacuum.xiaomi_vacuum_cleaner
  size: 25%

## buttons_general
x-buttons_general: &buttons_general
  global_settings:
    align: 'center middle'
    orientation: horizontal
    label:
      color:
        value: white
    label_sec:
      color:
        value: white
    icon:
      color:
        value: white
# -----------------------------

# -----------------------------
## Views
title: Home
views:
##### Licht #####
  - title: Licht
    id: light
    path: light
    icon: mdi:ceiling-light
    # popup_cards:
    #   light.lights_kitchen:
    #     title: Küchenlichter
    #     card:
    #       type: entities
    #       entities:
    #       - light.deckenlicht
    #       - light.steckdose_2
    #       - light.steckdose_4
    cards:
    - type: entities
      # title: Wohnzimmer 2
      show_header_toggle: false
      entities:
      - light.light_living_room_2
    - type: entities
      # title: Schlafzimmer
      show_header_toggle: false
      entities:
      - light.lights_bed_room
      - input_select.scenes_bed_room
      - type: custom:fold-entity-row
        head:
          type: section
          label: Lampen
        items:
          - light.light_bedroom
          - light.light_nightstand
    # - type: entities
    #   #title: Büro
    #   show_header_toggle: false
    #   entities:
    #     - light.sonoff_office
    # - type: entities
    #   #title: Küche
    #   show_header_toggle: false
    #   entities:
    #     - light.lights_kitchen
    - type: entities
      # title: Flur
      show_header_toggle: false
      entities:
      - light.light_entry
    - type: custom:tiles-card
      card_settings:
        columns: 1
        row_height: 45px
        padding: 10px
      <<: *buttons_general
      entities:
        - entity: light.lights_all
          label: Alle Lichter
          row: 1
          column: 1
          background:
            value_on: '#03A9F4'
            value_off: '#999999'
    - type: 'custom:compact-custom-header'
      main_config: true
      menu: show
      notifications: show
      options: show
      exceptions:
      - conditions:
          user_agent: iPhone
        config:
          options: hide

##### Heizung #####
  - title: Heizung
    id: radiator
    path: radiator
    icon: mdi:radiator
    cards:
    - type: 'custom:compact-custom-header'

#### Staubsauger #####
  - title: Staubsauger
    id: vacuum
    path: vacuum
    icon: mdi:robot-vacuum
    cards:
    - type: custom:vertical-stack-in-card
      cards:
      - type: entities
        show_header_toggle: false
        entities:
          - vacuum.xiaomi_vacuum_cleaner
          - sensor.xiaomi_vacuum_sensor_battery
          - type: section
      - type: horizontal-stack
        cards:
        - type: "custom:button-card"
          icon: mdi:play
          <<: *vacuum-buttons
          action: service
          service:
            domain: vacuum
            action: start
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
        - type: "custom:button-card"
          icon: mdi:pause
          <<: *vacuum-buttons
          action: service
          service:
            domain: vacuum
            action: pause
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
        - type: "custom:button-card"
          icon: mdi:home
          <<: *vacuum-buttons
          action: service
          service:
            domain: vacuum
            action: return_to_base
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
        - type: "custom:button-card"
          icon: mdi:map-marker
          <<: *vacuum-buttons
          action: service
          service:
            domain: vacuum
            action: locate
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
      - type: entities
        show_header_toggle: false
        entities:
          - type: custom:fold-entity-row
            head:
              type: section
              label: Automatisierung
            items:
              - automation.xiaomi_staubsauger_abwesenheit
              - automation.xiaomi_staubsauger_taglich_saugen
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Zonen (Räume)
                items:
                  # - input_select.vacuum_rooms
                  - script.vacuum_office      # Büro
                  - script.vacuum_living_room # Wohnzimmer
                  - script.vacuum_bed_room    # Schlafzimmer
                  - script.1543666985219 # Bad
                  - script.vacuum_kitchen # Küche
                  - script.1543666867257 # Flur
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Wartung
                items:
                  - automation.xiaomi_staubsauger_neustart
                  - automation.xiaomi_staubsauger_error_stop
                  - counter.xiaomo_errors
                  - type: section
                  - type: custom:fold-entity-row
                    head: sensor.xiaomi_vacuum_side_brush_left
                    items:
                      - script.1547995869377
                  - type: custom:fold-entity-row
                    head: sensor.xiaomi_vacuum_sensor_dirty_left
                    items:
                      - script.1547995682348
                  - type: custom:fold-entity-row
                    head: sensor.xiaomi_vacuum_main_brush_left
                    items:
                      - script.1547995909810
                  - type: custom:fold-entity-row
                    head: sensor.xiaomi_vacuum_filter_left
                    items:
                      - script.1547995832032
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Benachrichtigungen
                items:
                  - automation.xiaomi_staubsauger_fehler
                  - automation.xiaomi_staubsauger_fertig
                  - automation.xiaomi_staubsauger_gestartet
      - type: 'custom:compact-custom-header'

##### Musik #####
  - title: Musik
    id: music
    path: music
    icon: mdi:music-box-outline
    cards:
    - type: entities
      title: Sonos Wohnzimmer (small)
      show_header_toggle: false
      entities:
      - type: custom:mini-media-player
        entity: media_player.small
        <<: *music-player
        sonos:
          show_group_count: true
          sync_volume: true
          entities:
          - entity_id: media_player.big
            name: Sonos Wohnzimmer (big)
    - type: conditional
      conditions:
        - entity: sensor.sonos_grouped
          state: "off"
      card:
        type: entities
        #title: Sonos Bad
        entities:
          - type: custom:mini-media-player
            entity: media_player.big
            <<: *music-player
    - type: entities
      #title: Sonos Einstellungen
      show_header_toggle: false
      entities:
        - automation.sonos_starten
        - automation.sonos_stoppen
        - type: custom:fold-entity-row
          head:
            type: section
            label: Wecker
          items:
            - script.1534621188695
            - script.1534621226775
    - type: 'custom:compact-custom-header'

##### Personen #####
  - title: Personen
    id: presence
    path: presence
    icon: mdi:account-multiple
    cards:
    - type: entities
      #title: Anwesenheit
      show_header_toggle: false
      entities:
        - person.laura
        - person.tobias
        - type: section
        - automation.abwesenheitsschaltung
        - automation.anwesenheitsschaltung
    - type: 'custom:compact-custom-header'

##### Sonstiges #####
  - title: Sonstiges
    id: other
    path: other
    icon: mdi:library-books
    cards:
    #- type: entities
    #  show_header_toggle: false
    #  entities:
    #    - weather.dark_sky
    #    - sun.sun
    - type: custom:weather-card
      entity: weather.dark_sky
      icons: "/local/github/bramkragten/weather-card/icons/"
    - type: custom:tracker-card
    - type: 'custom:compact-custom-header'
